# -*- coding: utf-8 -*-
"""2_stemming .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFDqaO2JN8apZqALVUcxOTydLbsayVGS
"""

import nltk
from nltk.stem import PorterStemmer, LancasterStemmer
from nltk.stem import SnowballStemmer

# Sample words for stemming
words = ["running", "ran", "runs", "runner", "easily", "fairly", "fairness"]

# Porter Stemmer
porter_stemmer = PorterStemmer()
stemmed_words_porter = [porter_stemmer.stem(word) for word in words]
print("Porter Stemmer:", stemmed_words_porter)

# Lancaster Stemmer
lancaster_stemmer = LancasterStemmer()
stemmed_words_lancaster = [lancaster_stemmer.stem(word) for word in words]
print("Lancaster Stemmer:", stemmed_words_lancaster)


# Snowball Stemmer for English
snowball_stemmer = SnowballStemmer("english")
stemmed_words_snowball = [snowball_stemmer.stem(word) for word in words]
print("Snowball Stemmer:", stemmed_words_snowball)