# -*- coding: utf-8 -*-
"""6_ner .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFDqaO2JN8apZqALVUcxOTydLbsayVGS
"""

import spacy
from spacy import displacy

# Load the English language model
nlp = spacy.load("en_core_web_sm")

# Sample text for NER
text = """
Apple was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in 1976.
It is headquartered in Cupertino, California, United States.
Apple designs, manufactures, and sells consumer electronics, computer software,
and online services. Its best-known hardware products include the iPhone,
iPad, Mac, and Apple Watch.
"""

# Process the text with spaCy
doc = nlp(text)

# Extract named entities
named_entities = [(ent.text, ent.label_) for ent in doc.ents]

# Display named entities
print("Named Entities:")
for entity, label in named_entities:
    print(f"{entity} - {label}")

# Visualize named entities
displacy.render(doc, style="ent", jupyter=True)